[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=com.example.term"
class = "com.example.term"
position = "17% 6%"
size = "65% 60%"
offset = "500%"
